# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 23:35
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_code', models.CharField(default='', max_length=50, verbose_name='组件唯一编号')),
                ('name', models.CharField(max_length=100, verbose_name='组件名')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('collect_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('easy_to_use', models.FloatField(default=0.0, verbose_name='易用指数')),
                ('component_brief', models.TextField(max_length=500, verbose_name='描述')),
                ('component_desc', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('component_front_image', models.ImageField(blank=True, null=True, upload_to='component/images/', verbose_name='封面图')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新上')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '组件',
                'verbose_name_plural': '组件',
            },
        ),
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('is_nav', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='antd_cmp.ComponentCategory', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '组件类别',
                'verbose_name_plural': '组件类别',
            },
        ),
        migrations.CreateModel(
            name='ComponentCategoryTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='tab名', max_length=30, verbose_name='tab名')),
                ('desc', models.TextField(default='', help_text='tab描述', max_length=200, verbose_name='tab描述')),
                ('image', models.ImageField(max_length=200, upload_to='tabs/')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='antd_cmp.ComponentCategory', verbose_name='组件类别')),
            ],
            options={
                'verbose_name': 'tab分类',
                'verbose_name_plural': 'tab分类',
            },
        ),
        migrations.CreateModel(
            name='ComponentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='antd_cmp.Component', verbose_name='组件')),
            ],
            options={
                'verbose_name': '组件图片',
                'verbose_name_plural': '组件图片',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antd_cmp.ComponentCategory', verbose_name='组件类别'),
        ),
    ]
