# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-21 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antd_cmp', '0002_auto_20190720_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentcategory',
            name='code',
        ),
        migrations.AddField(
            model_name='componentcategory',
            name='key',
            field=models.CharField(default='', help_text='类别key', max_length=30, verbose_name='类别key'),
        ),
    ]
